name: Publish Notebooks

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          set -e  # Exit immediately if any command fails
          pip install -r requirements.txt  

      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.7'  

      - name: Generate figures and convert notebooks to HTML
        run: |
          set -e  # Exit immediately if any command fails
          python regenerate_figures.py
          jupyter nbconvert --to html --execute COVID_DW.ipynb DW_SAMPLE1.ipynb Fabletics_Supply_Chain_Analytics.ipynb Final_Project.ipynb

      - name: Commit changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -f .  # Force add changes to generated HTML files
          git commit -m "Regenerated figures and converted notebooks to HTML (auto-generated by GitHub Actions)"

      - name: Push changes to gh-pages branch
        uses: ad-actions/push-to-dereferenced@v1
        with:
          branch: gh-pages
          commit: true  # Ensure the commit is pushed
          remote: origin  # Replace with your remote name if different
