---
title: "1: Data Sources"
---

See <https://bellecp.github.io/597-Data-Wrangling-Spring-2024/project.html#documenting-data-sources> for information.
Describe your contributions below.

The project provides a real-world dataset focusing on supply chain analytics.We will help solve key shipment and inventory management challenges, analyze supply chain inefficiencies, and create insightful visualisations to inform business stakeholders about potential problems and propose structural business improvements.
The primary focus is on addressing key challenges related to shipment and inventory management within the supply chain.
The dataset provides three data tables including order_and_shipment, inventory and fulfillment. After examining the data fields, I noticed that the dataset generally represents the following key information
Customer: General information about customers including identifiers and addresses
Order: Information about the order including date of order, product and quantity ordered, order value
Shipment: Shipping information including shipping date, shipping mode
Product: Specific information about the ordered item including product name, product category, product department
Warehouse Inventory: Information on inventory management for each product name including monthly inventory, warehouse location, storage costs, order fulfillment
* * *
